### ISSUE TITLE
remove equals sign for uuid_pool in /ucs_server_templates/main.tf

### ISSUE THREAD

**Issue by nlazic123** [terraform-cisco-modules/terraform-intersight-imm#1]
equals sign for uuid_pool in https://github.com/terraform-cisco-modules/terraform-intersight-imm/blob/master/modules/ucs_server_templates/main.tf, should be removed, it is causing error 

"Inappropriate value for attribute "uuid_pool": list of object required."

uuid_pool = {
    moid        = var.uuid_pool
    object_type = "uuidpool.Pool"
  }

should be:
uuid_pool {
    moid        = var.uuid_pool
    object_type = "uuidpool.Pool"
  }

**Comment by scotttyso** [comment]
Added change.

@nlazic123 - I haven't updated this module since 2021.  The module I have been more regularly maintaining is the easy-imm module.  https://github.com/terraform-cisco-modules/easy-imm.

This module provides a simplified YAML input and has input validation and significantly simplified module structure.  Also, all the up-to-date support for newer policies and profile features are up to date in the newer module, and have not been back ported to this, which was my first attempt.  I would recommend at least checking out the new module.
